#!/usr/bin/env python

import sys
import re
import os
import platform
import shutil

files = [ "gitconfig", "vim", "vimrc", "myconfigs", "bashrc", "aliases" ]
mac_linux_only_files = [ "inputrc", "zshrc", "tmux.conf" ]

if platform.system() == "Windows":
  dir_delim = "\\"
else:
  dir_delm = "/"

def print_usage():
  global dir_delim
  print "Usage:"
  print "help\t\tPrint usage"
  print "install\t\tInstall dotfiles to ~" + dir_delim + ".<file>"
  print "uninstall\tUninstall dotfiles from ~" + dir_delim + ".<file>"

def get_platform_files():
  global files, mac_linux_only_files
  if (re.search(r"(linux|darwin)", sys.platform)):
    print "Running on on linux or Mac."
    files.extend(mac_linux_only_files)
    return files
  else:
    return files

def install():
  files_to_install = get_platform_files()

  os.chdir(os.path.abspath(os.path.dirname(__file__)))

  for file in files_to_install:
    if platform.system() == "Windows":
      fullpath = os.path.expanduser("~") + "\." + file
    else:
      fullpath = os.path.expanduser("~") + dir_delim + "." + file

    if os.path.exists(fullpath) or os.path.islink(fullpath):
      print "Removing %s... " % fullpath
      try:
        os.remove(fullpath)
      except(OSError):
        shutil.rmtree(fullpath)
    else:
      print "File %s not found..." % fullpath

    source = (os.path.expanduser("~") + dir_delim + "." + file)
    dest = os.path.realpath(os.path.dirname(__file__)) + dir_delim + file
    print "copying " + source + " to " + dest

    try:
      shutil.copy2(dest, source)
    except(IOError):
      shutil.copytree(dest, source)

def uninstall():
  files_to_uninstall = get_platform_files()
  for file in files_to_uninstall:
    fullpath = os.path.expanduser("~") + dir_delim + "." + file
    if os.path.exists(fullpath) or os.path.islink(fullpath):
      print "Removing " + fullpath + "..."
      try:
        os.unlink(fullpath)
      except:
        shutil.rmtree(fullpath)
    else:
      print "File %s not found..." % fullpath

if __name__ == "__main__":
  if len(sys.argv) != 2:
    print "setup takes one argument"
    print_usage()
    sys.exit()

  if sys.argv[1] == "install":
    install()
  elif sys.argv[1] == "uninstall":
    uninstall()
  elif sys.argv[1] == "help":
    print_usage()
  else:
    print "Command not valid"
    print_usage()
